server:
  port: 8300

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 是否确认回调
    publisher-confirm-type: correlated
    # 是否返回回调
    publisher-returns: true
    virtual-host: /
    # 手动确认
    listener:
      simple:
        acknowledge-mode: manual
  elasticsearch:
    rest:
      uris: 119.45.208.112:9200
  application:
    name: search-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
