server:
  port: 8300

spring:
  elasticsearch:
    rest:
      uris: 119.45.208.112:9200
  application:
    name: search-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
