server:
  port: 8200
spring:
  application:
    name: upload-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


mingrui:
  upload:
    path:
      windows: D:\\six\\images
      linux: /ckp/images
    img:
      host: http://119.45.208.112/
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: #缩略图
    width: 60
    height: 60
  tracker-list: #tracker地址
    - 119.45.208.112:22122